await knex.raw('DROP TABLE INICITALCONFIGS')
await knex.raw('DROP TABLE configs')

knex.raw(`
CREATE TABLE IF NOT EXISTS CONFIGS (
   FILIAL TEXT PRIMARY KEY,
   DB TEXT,
   HOST TEXT,
   USER TEXT,
   PASSWORD TEXT,
   INTERVALO INTEGER,
   TOKEN TEXT
);
`)